#   FATIAMENTO DE CARACTERES    #

#[] <-- LISTA
frase = 'Curso em Vídeo Python'

print(frase[1:10]) # <-- PRINTA SOMENTE APARTIR DA POSIÇÃO 1 ATÉ A POSIÇÃO 10 DA STRING
print(frase[1:10:2]) # <-- PRINTA BASEADO NA POSIÇÃO CITADA E PULA 2 CARACTERES DURANTE A LEITURA DA STRING
print(frase.count('a')) # <-- MOSTRA QUANTAS VEZES O CARACTERE 'a' (minusculo) FOI IDENTIFICADO NA VARIAVEL STRING

print(frase.replace('Python', 'Android')) # <-- SUBSTITUI UM CARACTER OU STRING POR OUTRA COISA

dividido = frase.split()# <-- REALIZADA A DIVISÃO DA STRING BASEADA NOS ESPAÇOS "VAZIOS" ENTRE ELAS CRIA-SE UMA LISTA

print(dividido[0]) # <-- PRINTA SOMENTE A POSIÇÃO SOLICITADA DA LISTA, APÓS REALIZADA A DIVISÃO DELA
print(dividido[2][2]) # <-- PRINTA A POSIÇÃO DA LISTA DESEJADA E RETORNA SOMENTE O 3° CARACTERE DO MESMO